# Generated by Django 4.2.19 on 2025-04-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_date_event_event_date_remove_event_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
