# Generated by Django 4.2.19 on 2025-04-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_reminder_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
